include:
  - project: "galileo/shared-ci"
    file: "global/variables.gitlab-ci.yml"

stages:
  - build
  - release

services:
  - name: 781817666983.dkr.ecr.us-east-1.amazonaws.com/docker.io/docker:20.10.13-dind-alpine3.15

build:
  stage: build
  image: rancher/dapper:v0.6.0
  before_script:
    - until docker info; do sleep 1; done
  script:
    - |
      apk add --no-cache curl
      dapper ci
      (cd dist/artifacts; sha256sum * > sha256sum-amd64.txt)
      if [ "$CI_COMMIT_TAG" ]; then
        curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file dist/artifacts/k3os-amd64.iso             ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/k3os-amd64.iso
        curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file dist/artifacts/k3os-initrd-amd64          ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/k3os-initrd-amd64
        curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file dist/artifacts/k3os-kernel-amd64.squashfs ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/k3os-kernel-amd64.squashfs
        curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file dist/artifacts/k3os-kernel-version-amd64  ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/k3os-kernel-version-amd64
        curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file dist/artifacts/k3os-rootfs-amd64.tar.gz   ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/k3os-rootfs-amd64.tar.gz
        curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file dist/artifacts/k3os-vmlinuz-amd64         ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/k3os-vmlinuz-amd64
        curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file dist/artifacts/sha256sum-amd64.txt        ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/sha256sum-amd64.txt
      fi
  timeout: 2 hours
  artifacts:
    paths:
      - "dist/artifacts/*"
    expire_in: 1 day
  only:
    refs:
      - web

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG && $CI_PIPELINE_SOURCE == "web"
  needs:
    - job: build
      artifacts: true
  script:
    - echo "Releasing $CI_COMMIT_TAG"
  release:
    name: '$CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    description: "k3os auto build"
    assets:
      links:
        - name: 'k3os-amd64.iso'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/k3os-amd64.iso'
        - name: 'k3os-initrd-amd64'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/k3os-initrd-amd64'
        - name: 'k3os-kernel-amd64.squashfs'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/k3os-kernel-amd64.squashfs'
        - name: 'k3os-kernel-version-amd64'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/k3os-kernel-version-amd64'
        - name: 'k3os-rootfs-amd64.tar.gz'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/k3os-rootfs-amd64.tar.gz'
        - name: 'k3os-vmlinuz-amd64'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/k3os-vmlinuz-amd64'
        - name: 'sha256sum-amd64.txt'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/sha256sum-amd64.txt'
